---

- name: Install dependencies
  apt: name=apt-transport-https
  tags:
    - node

- name: Add APT key
  apt_key: url=https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280  id=68576280
  tags:
    - node

- name: Add APT repository
  apt_repository: repo="{{item}}" update_cache=yes
  with_items:
  - "deb https://deb.nodesource.com/node_{{nodejs_major_version}} {{ansible_distribution_release}} main"
  - "deb-src https://deb.nodesource.com/node_{{nodejs_major_version}} {{ansible_distribution_release}} main"
  tags:
    - node

- name: Install specific version of nodejs
  apt: name=nodejs={{nodejs_version}}* state='present'
  update_cache: yes
  when: nodejs_version != 'latest'
  tags:
    - node

- name: Install latest version of nodejs
  apt: name=nodejs state='latest'
  update_cache: yes
  when: nodejs_version == 'latest'
  tags:
    - node

# Latest packages doesn't have 'node' executable anymore
# It were renamed to 'nodejs'. Add link to support old
# cookbooks which use the legacy 'node' command.
- stat: path=/usr/bin/node
  register: node_bin
  tags:
    - node

- name: Add legacy node link
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
  when: not node_bin.stat.exists
  tags:
    - node
