---

- apt: name=git state=present force=yes

- name: Setup the Git repo
  become: yes
  become_user: "{{ application_user }}"
  git: repo={{ git_repo }}
       version={{ git_branch }}
       dest={{ application_source_path }}
       accept_hostkey=yes
       force=yes
  tags:
    - deploy

- name: Create env file
  template: src=env.j2
            dest={{ application_source_path }}/.env
            owner={{ application_user }}
            group={{ application_group }}
            mode=0640
            backup=no
  tags:
    - deploy
